# Generated by Django 4.2.1 on 2023-05-31 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_photoname_photonameurls_delete_photourl_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='photoNameUrls',
            new_name='PostImages',
        ),
        migrations.RenameModel(
            old_name='photoName',
            new_name='PostName',
        ),
    ]
