# Generated by Django 4.2.1 on 2023-05-31 05:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_photonameurls_postimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoNameUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoUrl', models.CharField(max_length=300)),
                ('videoName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.videoname')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoUrl',
        ),
        migrations.AddField(
            model_name='postname',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
