# Generated by Django 4.2.1 on 2023-05-31 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_videoname_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videonameurls',
            old_name='videoName',
            new_name='videoTitle',
        ),
    ]
