# Generated by Django 4.2.1 on 2023-06-06 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_videoname_videonameurls_videotitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdultNewsUrl',
        ),
        migrations.DeleteModel(
            name='TenderUrl',
        ),
        migrations.AddField(
            model_name='newsurl',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
