# Generated by Django 4.2.1 on 2023-06-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_delete_adultnewsurl_delete_tenderurl_newsurl_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.FileField(upload_to='projectImage/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('projectName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.projectname')),
            ],
        ),
        migrations.DeleteModel(
            name='AnoncUrl',
        ),
        migrations.DeleteModel(
            name='AutobiUrl',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EventUrl',
        ),
        migrations.DeleteModel(
            name='LectureUrl',
        ),
        migrations.DeleteModel(
            name='VacancyUrl',
        ),
        migrations.RemoveField(
            model_name='videonameurls',
            name='videoTitle',
        ),
        migrations.DeleteModel(
            name='VideoName',
        ),
        migrations.DeleteModel(
            name='VideoNameUrls',
        ),
    ]
