# Generated by Django 4.2.1 on 2023-06-19 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_newsurl_related_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalfilesurl',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
