# Generated by Django 4.2.1 on 2023-06-19 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_journalfilesurl_type_of_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalfilesurl',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
